version: '3'

services:

  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_ENABLE_V2=true
      - ETCDL_API=2
    networks:
      - default
    restart: always
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.labels.name==dtwins1

  mqtt-cluster:
    image: "emqx/emqx:4.3.8"
    environment:
      - EMQX_ZONE__EXTERNAL__MAX_MQUEUE_LEN=0
      - EMQX_CLUSTER__DISCOVERY=etcd
      - EMQX_CLUSTER__ETCD__SERVER=http://etcd:2379
      - EMQX_CLUSTER__ETCD__PREFIX=emqcl
      - EMQX_CLUSTER__ETCD__NODE_TTL=1m
      - EMQX_ZONE__EXTERNAL__MQUEUE_PRIORITIES=A/A/A=10,A/E/E=5
    networks:
      default:
        aliases:
          - emqx_n1.mq.tt
    restart: always
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.labels.name==dtwins1
  
  client_accel:
    image: "opendigitaltwin/dt-client-accel:latest"
    depends_on:
      - mqtt-broker
      - twin
    environment:
      - RUST_LOG=info
      - CONTAINER_DELAY_S=20
      - MQTT_BROKER_ADDRESS=mqtt-cluster
      - MQTT_BROKER_PORT=1883
      - MQTT_CLIENT_QOS=1
      - MQTT_CLIENT_BUFFER_BYTE_SIZE=64
      - MQTT_CLIENT_MESSAGES_TO_SEND=50000
      - MQTT_CLIENT_MESSAGE_DELAY_MS=50
      - MQTT_CLIENT_TOPIC=A/A/A
      - MQTT_CLIENT_ACCEL_FACTOR=2
      - MQTT_CLIENT_ACCEL_EACH=1000
      - GEOMETRIC=truegit
    networks:
      - default
    deploy:
      replicas: 0
      placement:    
        constraints:
          - node.labels.name==dtwins2
    command: dt-client-accel

  twin:
    image: "opendigitaltwin/dt-instance:latest"
    depends_on:
      - mqtt-broker
    environment:
      - MQTT_BROKER_ADDRESS=mqtt-cluster
      - MQTT_BROKER_PORT=1883
      - MQTT_INSTANCE_QOS=1
      - RUST_LOG=info
      - DB_ADDRESS=scylla-db:9042
      - TWIN_INSTANCE=38162cb0-e585-43d7-b55d-5c240b2bfb7c
      - MQTT_SUBSCRIBED_TOPIC=A/A/#
    networks:
      - default
    restart: always
    deploy:
      replicas: 0
      placement:    
        constraints:
          - node.labels.name==dtwins2
    command: dt-instance
    
  mqtt-broker-manager:
    image: "teste:latest"
    environment:
      - MQTT_BROKER_ADDRESS=mqtt-cluster
      - MQTT_BROKER_PORT=8081
      - MQTT_API_FREQ=1
      - CLUSTER_SAVES=5
      - MAX_QUEUE= 200
      - RUST_LOG=info
    networks:
      - default
    restart: always
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.labels.name==dtwins1
    command: dt-mqtt-manager

networks:
  default:
