version: '3'

services:

  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_ENABLE_V2=true
      - ETCDL_API=2
    networks:
      - default
    restart: always
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.labels.name==dtwins3

  mqtt-cluster:
    image: "emqx/emqx:4.3.8"
    environment:
      - EMQX_ZONE__EXTERNAL__MAX_MQUEUE_LEN=0
      - EMQX_ZONE__EXTERNAL__MAX_INFLIGHT=32
      - EMQX_CLUSTER__DISCOVERY=etcd
      - EMQX_CLUSTER__ETCD__SERVER=http://etcd:2379
      - EMQX_CLUSTER__ETCD__PREFIX=emqcl
      - EMQX_CLUSTER__ETCD__NODE_TTL=1m
      - EMQX_ZONE__EXTERNAL__MQUEUE_PRIORITIES=A/A/A=10,A/E/E=5
    networks:
      default:
    restart: always
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.labels.size==edge

  mqtt-manager:
    image: "opendigitaltwin/dt-mqtt-manager:latest"
    environment:
      - MQTT_API_ADDRESS=mqtt-cluster
      - MQTT_API_PORT=8081
      - MQTT_API_FREQ=15
      - SWARM_API_ADDRESS=192.168.122.17
      - SWARM_API_PORT=2375
      - CLUSTER_SAVES=1
      - MAX_QUEUE=200
      - MAX_INFLIGHT=32
      - SCALE_BLOCK_TIME=30
      - RUST_LOG=info
    networks:
      - default
    restart: always
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.labels.name==dtwins1
    command: dt-mqtt-manager
  
  clients-A:
    image: "opendigitaltwin/dt-client-bytes:latest"
    depends_on:
      - twin
    environment:
      - RUST_LOG=info
      - CONTAINER_DELAY_S=20
      - MQTT_BROKER_ADDRESS=mqtt-cluster
      - MQTT_BROKER_PORT=1883
      - MQTT_CLIENT_QOS=1
      - MQTT_CLIENT_BUFFER_BYTE_SIZE=64
      - MQTT_CLIENT_MESSAGES_TO_SEND=7500
      - MQTT_CLIENT_MESSAGE_DELAY_MS=100
      - MQTT_CLIENT_TOPIC=A/A/A
      - MQTT_AMOUNT_OF_CLIENTS=200
      - MQTT_THREAD_DELAY=5
    networks:
      - default
    deploy:
      replicas: 0
      placement:    
        constraints:
          - node.labels.name==dtwins1
    command: dt-client-bytes

  clients-B:
    image: "opendigitaltwin/dt-client-bytes:latest"
    depends_on:
      - twin
    environment:
      - RUST_LOG=info
      - CONTAINER_DELAY_S=0
      - MQTT_BROKER_ADDRESS=mqtt-cluster
      - MQTT_BROKER_PORT=1883
      - MQTT_CLIENT_QOS=1
      - MQTT_CLIENT_BUFFER_BYTE_SIZE=64
      - MQTT_CLIENT_MESSAGES_TO_SEND=7500
      - MQTT_CLIENT_MESSAGE_DELAY_MS=100
      - MQTT_CLIENT_TOPIC=A/B/B
      - MQTT_AMOUNT_OF_CLIENTS=100
      - MQTT_THREAD_DELAY=5
    networks:
      - default
    deploy:
      replicas: 0
      placement:    
        constraints:
          - node.labels.name==dtwins2
    command: dt-client-bytes

  clients-C:
    image: "opendigitaltwin/dt-client-bytes:latest"
    depends_on:
      - twin
    environment:
      - RUST_LOG=info
      - CONTAINER_DELAY_S=0
      - MQTT_BROKER_ADDRESS=mqtt-node
      - MQTT_BROKER_PORT=1883
      - MQTT_CLIENT_QOS=1
      - MQTT_CLIENT_BUFFER_BYTE_SIZE=64
      - MQTT_CLIENT_MESSAGES_TO_SEND=5000
      - MQTT_CLIENT_MESSAGE_DELAY_MS=100
      - MQTT_CLIENT_TOPIC=A/C/C
      - MQTT_AMOUNT_OF_CLIENTS=50
      - MQTT_THREAD_DELAY=5
    networks:
      - default
    deploy:
      replicas: 0
      placement:    
        constraints:
          - node.labels.name==dtwins7
    command: dt-client-bytes

  clients-D:
    image: "opendigitaltwin/dt-client-bytes:latest"
    depends_on:
      - twin
    environment:
      - RUST_LOG=info
      - CONTAINER_DELAY_S=0
      - MQTT_BROKER_ADDRESS=mqtt-node
      - MQTT_BROKER_PORT=1883
      - MQTT_CLIENT_QOS=1
      - MQTT_CLIENT_BUFFER_BYTE_SIZE=64
      - MQTT_CLIENT_MESSAGES_TO_SEND=5000
      - MQTT_CLIENT_MESSAGE_DELAY_MS=100
      - MQTT_CLIENT_TOPIC=A/D/D
      - MQTT_AMOUNT_OF_CLIENTS=50
      - MQTT_THREAD_DELAY=5
    networks:
      - default
    deploy:
      replicas: 0
      placement:    
        constraints:
          - node.labels.name==dtwins7
    command: dt-client-bytes

  twin-A:
    image: "opendigitaltwin/dt-instance:latest"
    depends_on:
      - mqtt-broker
    environment:
      - MQTT_BROKER_ADDRESS=mqtt-cluster
      - MQTT_BROKER_PORT=1883
      - MQTT_INSTANCE_QOS=1
      - RUST_LOG=info
      - DB_ADDRESS=scylla-db:9042
      - TWIN_INSTANCE=38162cb0-e585-43d7-b55d-5c240b2bfb7c
      - MQTT_SUBSCRIBED_TOPIC=A/A/#
    networks:
      - default
    restart: always
    deploy:
      replicas: 0
      placement:    
        constraints:
          - node.labels.name==dtwins1
    command: dt-instance

  twin-B:
    image: "opendigitaltwin/dt-instance:latest"
    depends_on:
      - mqtt-cluster
    environment:
      - MQTT_BROKER_ADDRESS=mqtt-cluster
      - MQTT_BROKER_PORT=1883
      - MQTT_INSTANCE_QOS=1
      - RUST_LOG=info
      - DB_ADDRESS=scylla-db:9042
      - TWIN_INSTANCE=38162cb0-e585-43d7-b55d-5c240b2bfb7c
      - MQTT_SUBSCRIBED_TOPIC=A/B/#
    networks:
      - default
    restart: always
    deploy:
      replicas: 0
      placement:    
        constraints:
          - node.labels.name==dtwins2
    command: dt-instance

  twin-C:
    image: "opendigitaltwin/dt-instance:latest"
    depends_on:
      - mqtt-cluster
    environment:
      - MQTT_BROKER_ADDRESS=mqtt-cluster
      - MQTT_BROKER_PORT=1883
      - MQTT_INSTANCE_QOS=1
      - RUST_LOG=info
      - DB_ADDRESS=scylla-db:9042
      - TWIN_INSTANCE=38162cb0-e585-43d7-b55d-5c240b2bfb7c
      - MQTT_SUBSCRIBED_TOPIC=A/C/#
    networks:
      - default
    restart: always
    deploy:
      replicas: 0
      placement:    
        constraints:
          - node.labels.name==dtwins7
    command: dt-instance

  twin-D:
    image: "opendigitaltwin/dt-instance:latest"
    depends_on:
      - mqtt-cluster
    environment:
      - MQTT_BROKER_ADDRESS=mqtt-cluster
      - MQTT_BROKER_PORT=1883
      - MQTT_INSTANCE_QOS=1
      - RUST_LOG=info
      - DB_ADDRESS=scylla-db:9042
      - TWIN_INSTANCE=38162cb0-e585-43d7-b55d-5c240b2bfb7c
      - MQTT_SUBSCRIBED_TOPIC=A/D/#
    networks:
      - default
    restart: always
    deploy:
      replicas: 0
      placement:    
        constraints:
          - node.labels.name==dtwins7
    command: dt-instance
  
networks:
  default:
