version: '3'
services:

  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_ENABLE_V2=true
      - ETCDL_API=2
    networks:
      - default
    restart: always
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.labels.name==manager

  mqtt-cluster:
    image: "emqx/emqx:4.3.8"
    environment:
      - EMQX_ZONE__EXTERNAL__MAX_MQUEUE_LEN=0
      - EMQX_ZONE__EXTERNAL__MAX_INFLIGHT=32
      - EMQX_CLUSTER__DISCOVERY=etcd
      - EMQX_CLUSTER__ETCD__SERVER=http://etcd:2379
      - EMQX_CLUSTER__ETCD__PREFIX=emqcl
      - EMQX_CLUSTER__ETCD__NODE_TTL=1m
    networks:
      default:
    restart: always
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.labels.name==cluster

  mqtt-manager:
    image: "opendigitaltwin/dt-mqtt-manager:latest"
    environment:
      - MQTT_API_ADDRESS=mqtt-cluster
      - MQTT_API_PORT=8081
      - MQTT_API_FREQ=15
      - SWARM_API_ADDRESS=192.168.123.229
      - SWARM_API_PORT=2375
      - CLUSTER_SAVES=1
      - MAX_QUEUE=5000
      - MAX_INFLIGHT=0
      - SCALE_BLOCK_TIME=30
      - RUST_LOG=info
    networks:
      - default
    restart: always
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.labels.name==manager
    command: dt-mqtt-manager

  # A e B são Twins de Sensores, que envia mensagens a cada 50ms 
  clients-A:
    image: "opendigitaltwin/dt-client-bytes:latest"
    depends_on:
      - twin
    environment:
      - RUST_LOG=info
      - CONTAINER_DELAY_S=20
      - MQTT_BROKER_ADDRESS=mqtt-cluster
      - MQTT_BROKER_PORT=1883
      - MQTT_CLIENT_QOS=1
      - MQTT_CLIENT_BUFFER_BYTE_SIZE=64
      - MQTT_CLIENT_MESSAGES_TO_SEND=10000
      - MQTT_CLIENT_MESSAGE_DELAY_MS=50
      - MQTT_CLIENT_TOPIC=A/A/A
      - MQTT_AMOUNT_OF_CLIENTS=800
      - MQTT_THREAD_DELAY=5
    networks:
      - default
    deploy:
      replicas: 0
      placement:    
        constraints:
          - node.labels.name==w01
    command: dt-client-bytes

  clients-B:
    image: "opendigitaltwin/dt-client-bytes:latest"
    depends_on:
      - twin
    environment:
      - RUST_LOG=info
      - CONTAINER_DELAY_S=0
      - MQTT_BROKER_ADDRESS=mqtt-cluster
      - MQTT_BROKER_PORT=1883
      - MQTT_CLIENT_QOS=1
      - MQTT_CLIENT_BUFFER_BYTE_SIZE=64
      - MQTT_CLIENT_MESSAGES_TO_SEND=10000
      - MQTT_CLIENT_MESSAGE_DELAY_MS=50
      - MQTT_CLIENT_TOPIC=A/B/B
      - MQTT_AMOUNT_OF_CLIENTS=700
      - MQTT_THREAD_DELAY=5
    networks:
      - default
    deploy:
      replicas: 0
      placement:    
        constraints:
          - node.labels.name==w02
    command: dt-client-bytes

#Clientes C e D são Baseados em câmeras
  clients-C:
    image: "opendigitaltwin/dt-client-bytes:latest"
    depends_on:
      - twin
    environment:
      - RUST_LOG=info
      - CONTAINER_DELAY_S=0
      - MQTT_BROKER_ADDRESS=mqtt-cluster
      - MQTT_BROKER_PORT=1883
      - MQTT_CLIENT_QOS=1
      - MQTT_CLIENT_BUFFER_BYTE_SIZE=1000
      - MQTT_CLIENT_MESSAGES_TO_SEND=1667
      - MQTT_CLIENT_MESSAGE_DELAY_MS=300
      - MQTT_CLIENT_TOPIC=A/C/C
      - MQTT_AMOUNT_OF_CLIENTS=600
      - MQTT_THREAD_DELAY=5
    networks:
      - default
    deploy:
      replicas: 0
      placement:    
        constraints:
          - node.labels.name==w03
    command: dt-client-bytes

  clients-D:
    image: "opendigitaltwin/dt-client-bytes:latest"
    depends_on:
      - twin
    environment:
      - RUST_LOG=info
      - CONTAINER_DELAY_S=0
      - MQTT_BROKER_ADDRESS=mqtt-cluster
      - MQTT_BROKER_PORT=1883
      - MQTT_CLIENT_QOS=1
      - MQTT_CLIENT_BUFFER_BYTE_SIZE=1000
      - MQTT_CLIENT_MESSAGES_TO_SEND=1667
      - MQTT_CLIENT_MESSAGE_DELAY_MS=300
      - MQTT_CLIENT_TOPIC=A/D/D
      - MQTT_AMOUNT_OF_CLIENTS=500
      - MQTT_THREAD_DELAY=5
    networks:
      - default
    deploy:
      replicas: 0
      placement:    
        constraints:
          - node.labels.name==w04
    command: dt-client-bytes

# Twins E e F usam padrões de automacão discretos
  clients-E:
    image: "opendigitaltwin/dt-client-bytes:latest"
    depends_on:
      - twin
    environment:
      - RUST_LOG=info
      - CONTAINER_DELAY_S=0
      - MQTT_BROKER_ADDRESS=mqtt-cluster
      - MQTT_BROKER_PORT=1883
      - MQTT_CLIENT_QOS=1
      - MQTT_CLIENT_BUFFER_BYTE_SIZE=64
      - MQTT_CLIENT_MESSAGES_TO_SEND=50000
      - MQTT_CLIENT_MESSAGE_DELAY_MS=10
      - MQTT_CLIENT_TOPIC=A/E/E
      - MQTT_AMOUNT_OF_CLIENTS=80
      - MQTT_THREAD_DELAY=10
    networks:
      - default
    deploy:
      replicas: 0
      placement:    
        constraints:
          - node.labels.name==w05
    command: dt-client-bytes

  clients-F:
    image: "opendigitaltwin/dt-client-bytes:latest"
    depends_on:
      - twin
    environment:
      - RUST_LOG=info
      - CONTAINER_DELAY_S=0
      - MQTT_BROKER_ADDRESS=mqtt-cluster
      - MQTT_BROKER_PORT=1883
      - MQTT_CLIENT_QOS=1
      - MQTT_CLIENT_BUFFER_BYTE_SIZE=64
      - MQTT_CLIENT_MESSAGES_TO_SEND=50000
      - MQTT_CLIENT_MESSAGE_DELAY_MS=10
      - MQTT_CLIENT_TOPIC=A/F/F
      - MQTT_AMOUNT_OF_CLIENTS=60
      - MQTT_THREAD_DELAY=10
    networks:
      - default
    deploy:
      replicas: 0
      placement:    
        constraints:
          - node.labels.name==w06
    command: dt-client-bytes

  twin-A:
    image: "opendigitaltwin/dt-instance:latest"
    depends_on:
      - mqtt-broker
    environment:
      - MQTT_BROKER_ADDRESS=mqtt-cluster
      - MQTT_BROKER_PORT=1883
      - MQTT_INSTANCE_QOS=1
      - RUST_LOG=info
      - DB_ADDRESS=scylla-db:9042
      - TWIN_INSTANCE=38162cb0-e585-43d7-b55d-5c240b2bfb7c
      - MQTT_SUBSCRIBED_TOPIC=A/A/#
    networks:
      - default
    restart: always
    deploy:
      replicas: 0
      placement:    
        constraints:
          - node.labels.name==w01
    command: dt-instance

  twin-B:
    image: "opendigitaltwin/dt-instance:latest"
    depends_on:
      - mqtt-cluster
    environment:
      - MQTT_BROKER_ADDRESS=mqtt-cluster
      - MQTT_BROKER_PORT=1883
      - MQTT_INSTANCE_QOS=1
      - RUST_LOG=info
      - DB_ADDRESS=scylla-db:9042
      - TWIN_INSTANCE=38162cb0-e585-43d7-b55d-5c240b2bfb7c
      - MQTT_SUBSCRIBED_TOPIC=A/B/#
    networks:
      - default
    restart: always
    deploy:
      replicas: 0
      placement:    
        constraints:
          - node.labels.name==w02
    command: dt-instance

  twin-C:
    image: "opendigitaltwin/dt-instance:latest"
    depends_on:
      - mqtt-cluster
    environment:
      - MQTT_BROKER_ADDRESS=mqtt-cluster
      - MQTT_BROKER_PORT=1883
      - MQTT_INSTANCE_QOS=1
      - RUST_LOG=info
      - DB_ADDRESS=scylla-db:9042
      - TWIN_INSTANCE=38162cb0-e585-43d7-b55d-5c240b2bfb7c
      - MQTT_SUBSCRIBED_TOPIC=A/C/#
    networks:
      - default
    restart: always
    deploy:
      replicas: 0
      placement:    
        constraints:
          - node.labels.name==w03
    command: dt-instance

  twin-D:
    image: "opendigitaltwin/dt-instance:latest"
    depends_on:
      - mqtt-cluster
    environment:
      - MQTT_BROKER_ADDRESS=mqtt-cluster
      - MQTT_BROKER_PORT=1883
      - MQTT_INSTANCE_QOS=1
      - RUST_LOG=info
      - DB_ADDRESS=scylla-db:9042
      - TWIN_INSTANCE=38162cb0-e585-43d7-b55d-5c240b2bfb7c
      - MQTT_SUBSCRIBED_TOPIC=A/D/#
    networks:
      - default
    restart: always
    deploy:
      replicas: 0
      placement:    
        constraints:
          - node.labels.name==w04
    command: dt-instance

  twin-E:
    image: "opendigitaltwin/dt-instance:latest"
    depends_on:
      - mqtt-cluster
    environment:
      - MQTT_BROKER_ADDRESS=mqtt-cluster
      - MQTT_BROKER_PORT=1883
      - MQTT_INSTANCE_QOS=1
      - RUST_LOG=info
      - DB_ADDRESS=scylla-db:9042
      - TWIN_INSTANCE=38162cb0-e585-43d7-b55d-5c240b2bfb7c
      - MQTT_SUBSCRIBED_TOPIC=A/E/#
    networks:
      - default
    restart: always
    deploy:
      replicas: 0
      placement:    
        constraints:
          - node.labels.name==w05
    command: dt-instance

  twin-F:
    image: "opendigitaltwin/dt-instance:latest"
    depends_on:
      - mqtt-cluster
    environment:
      - MQTT_BROKER_ADDRESS=mqtt-cluster
      - MQTT_BROKER_PORT=1883
      - MQTT_INSTANCE_QOS=1
      - RUST_LOG=info
      - DB_ADDRESS=scylla-db:9042
      - TWIN_INSTANCE=38162cb0-e585-43d7-b55d-5c240b2bfb7c
      - MQTT_SUBSCRIBED_TOPIC=A/F/#
    networks:
      - default
    restart: always
    deploy:
      replicas: 0
      placement:    
        constraints:
          - node.labels.name==w06
    command: dt-instance
 
networks:
  default:
