version: '3'

services:
    
  mqtt-node1:
    image: "emqx/emqx:latest"
    environment:
      - EMQX_NAME=node1
      - EMQX_HOST=emqx_n1.mq.tt
      - EMQX_ZONE__EXTERNAL__MAX_MQUEUE_LEN=0
      - EMQX_MQTT__MAX_PACKET_SIZE=64KB
      - EMQX_CLUSTER__DISCOVERY=static
      - EMQX_CLUSTER__STATIC__SEEDS=node1@emqx_n1.mq.tt, cluster@emqx_n2.mq.tt
    networks:
      default:
        aliases:
          - emqx_n1.mq.tt
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.name==dtwins1

  mqtt-node2:
    image: "emqx/emqx:latest"
    environment:
      - EMQX_NAME=node2
      - EMQX_HOST=emqx_n2.mq.tt
      - EMQX_ZONE__EXTERNAL__MAX_MQUEUE_LEN=0
      - EMQX_MQTT__MAX_PACKET_SIZE=64KB
      - EMQX_CLUSTER__DISCOVERY=static
      - EMQX_CLUSTER__STATIC__SEEDS=node1@emqx_n1.mq.tt, node2@emqx_n2.mq.tt
    networks:
      default:
        aliases:
          - emqx_n2.mq.tt
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.name==dtwins1

  scylla-db:
    image: scylladb/scylla
    networks:
      - default
    volumes:
      - ~/var/lib/scylla:/var/lib/scylla
    deploy:
      placement:
        constraints:
         - node.labels.name==dtwins1
networks:
  default:
