version: '3'

services:
  client:
    image: "opendigitaltwin/dt-client-bytes:latest"
    depends_on:
      - mqtt-broker
      - twin
    environment:
      - RUST_LOG=info
      - MQTT_BROKER_ADDRESS=mqtt-broker
      - MQTT_BROKER_PORT=1883
      - MQTT_CLIENT_QOS=1
      - MQTT_CLIENT_BUFFER_BYTE_SIZE=64
      - MQTT_CLIENT_MESSAGES_TO_SEND=1000
      - MQTT_CLIENT_MESSAGE_DELAY_MS=10
      - MQTT_CLIENT_TOPIC=A/A/A
    networks:
      - default
    deploy:
      replicas: 1
      placement:    
        constraints:
          - node.labels.name==dtwins1
    command: dt-client-bytes

  twin:
    image: "opendigitaltwin/dt-instance:latest"
    depends_on:
      - mqtt-node
      - scylla-db
    environment:
      - MQTT_BROKER_ADDRESS=mqtt-node
      - MQTT_BROKER_PORT=1883
      - MQTT_INSTANCE_QOS=1
      - RUST_LOG=info
      - DB_ADDRESS=scylla-db:9042
      - TWIN_INSTANCE=38162cb0-e585-43d7-b55d-5c240b2bfb7c
      - MQTT_SUBSCRIBED_TOPIC=A/A/A
    networks:
      - default
    restart: always
    deploy:
      placement:    
        constraints:
          - node.labels.name==dtwins1
    command: dt-instance
    
  mqtt-emqx:
    image: "emqx/emqx:latest"
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=emqx_n1.mq.tt
      - EMQX_ZONE__EXTERNAL__MAX_MQUEUE_LEN=0
      - EMQX_MQTT__MAX_PACKET_SIZE=64KB
    networks:
      default:
        aliases:
          - emqx_n1.mq.tt
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.name==dtwins1

  mqtt-node:
    image: "emqx/emqx:latest"
    environment:
      - EMQX_NAME=node
      - EMQX_HOST=emqx_n2.mq.tt
      - EMQX_ZONE__EXTERNAL__MAX_MQUEUE_LEN=0
      - EMQX_MQTT__MAX_PACKET_SIZE=64KB
      - EMQX_CLUSTER__DISCOVERY=dns
      - EMQX_CLUSTER__DNS__NAME=mqtt_n1.mq.tt
      - EMQX_CLUSTER__DNS__APP=emqx
    networks:
      default:
        aliases:
	        - emqx_n2.mq.tt
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.name==dtwins1

  scylla-db:
    image: scylladb/scylla
    networks:
      - default
    volumes:
      - ~/var/lib/scylla:/var/lib/scylla
    deploy:
      placement:
        constraints:
         - node.labels.name==dtwins1
networks:
  default:
