version: '3'

services:

  mqtt-emqx:
    image: "emqx/emqx:latest"
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=emqx_n1.mq.tt
      - EMQX_ZONE__EXTERNAL__MAX_MQUEUE_LEN=0
      - EMQX_MQTT__MAX_PACKET_SIZE=64KB
      - EMQX_CLUSTER__DISCOVERY=dns
      - EMQX_CLUSTER__DNS__APP=emqx_n2.mq.tt
      - EMQX_CLUSTER__DNS__NAME=emqx
    networks:
      default:
        aliases:
          - emqx_n1.mq.tt
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.name==dtwins1

  mqtt-node:
    image: "emqx/emqx:latest"
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=emqx_n2.mq.tt
      - EMQX_ZONE__EXTERNAL__MAX_MQUEUE_LEN=0
      - EMQX_MQTT__MAX_PACKET_SIZE=64KB
      - EMQX_CLUSTER__DISCOVERY=dns
      - EMQX_CLUSTER__DNS__NAME=emqx_n1.mq.tt
      - EMQX_CLUSTER__DNS__APP=emqx
    networks:
      default:
        aliases:
          - emqx_n2.mq.tt
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.name==dtwins1
          
networks:
  default:
