version: '3'

services:

  mqtt-node1:
    image: "emqx/emqx:latest"
    environment:
      - EMQX_NAME=node1
      - EMQX_HOST=emqx_n1.mq.tt
      - EMQX_ZONE__EXTERNAL__MAX_MQUEUE_LEN=0
      - EMQX_CLUSTER__DISCOVERY=mcast
      - EMQX_CLUSTER__MCAST__ADDR=mqtt-node2
      - EMQX_CLUSTER__MCAST__TTL=255
      - EMQX_CLUSTER__MCAST__PORTS=4369,4370
      - EMQX_CLUSTER__MCAST__IFACE=0.0.0.0
      - EMQX_CLUSTER__MCAST__LOOP=on
    networks:
      default:
        aliases:
          - emqx_n1.mq.tt
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.name==dtwins1

  mqtt-node2:
    image: "emqx/emqx:latest"
    environment:
      - EMQX_NAME=node2
      - EMQX_HOST=emqx_n2.mq.tt
      - EMQX_ZONE__EXTERNAL__MAX_MQUEUE_LEN=0
    networks:
      default:
        aliases:
          - emqx_n2.mq.tt
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.name==dtwins1

networks:
  default:
